# Generated by Django 5.1 on 2024-09-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksList', '0002_alter_books_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreviews',
            name='Review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='Author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='BookName',
            field=models.CharField(max_length=150),
        ),
    ]
