# Generated by Django 5.1 on 2024-09-04 07:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksList', '0004_bookreviews_dateadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='Date_Added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stores',
            name='Date_Added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
