# Generated by Django 5.1 on 2024-09-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BooksList', '0006_stores_bookstoadd_stores_bookstodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stores',
            name='Date_Added',
        ),
        migrations.RemoveField(
            model_name='stores',
            name='booksToAdd',
        ),
        migrations.RemoveField(
            model_name='stores',
            name='booksToDel',
        ),
    ]
