# Generated by Django 5.1 on 2024-09-04 08:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksList', '0007_remove_stores_date_added_remove_stores_bookstoadd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='Date_Added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
