# Generated by Django 5.1 on 2024-09-27 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JwtAuthenticationConfig', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForgetPassword',
        ),
    ]
