# Generated by Django 5.1 on 2024-09-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JwtAuthenticationConfig', '0002_delete_forgetpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='abc', max_length=24, unique=True),
        ),
    ]
