# Generated by Django 5.1 on 2024-09-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JwtAuthenticationConfig', '0003_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='abc', max_length=24),
        ),
    ]
