# Generated by Django 5.1 on 2024-09-27 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JwtAuthenticationConfig', '0004_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
