# Generated by Django 5.1 on 2024-09-27 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JwtAuthenticationConfig', '0005_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
