# Generated by Django 5.1 on 2024-09-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JwtAuthenticationConfig', '0006_remove_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
